config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  get '/logout', to: 'sessions#destroy'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'

  resources :users, only: [:new, :create, :show]

  namespace :admin do
    resources :categories, only: [:index, :new, :create, :destroy]
    resources :images, only: [:index, :new, :create]
  end

  resources :users do
    resources :ideas
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates_presence_of :name

  has_many :ideas
end

app/models/idea.rb
class Idea < ApplicationRecord
  validates_presence_of :title, :description

  belongs_to :user
  belongs_to :category
  has_many :idea_images
  has_many :images, through: :idea_images
end

app/models/idea_image.rb
class IdeaImage < ApplicationRecord
  belongs_to :image
  belongs_to :idea
end

app/models/image.rb
class Image < ApplicationRecord
  validates_presence_of :name, :url

  has_many :idea_images
  has_many :ideas, through: :idea_images
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, uniqueness: true, presence: true
  validates_presence_of :password, require: true
  validates_presence_of :email, :country, :role

  has_many :ideas

  has_secure_password

  enum role: ['default', 'admin']
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :require_admin

  def require_admin
    render file: "/public/404" unless current_admin?
  end
  
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  before_action :require_admin

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if current_admin?
      @category.save
      redirect_to admin_categories_path
    else
      render :new
    end
  end

  def destroy
    @category = Category.find(params[:id])
    if current_admin?
      @category.destroy
      # flash[:success] = "#{@category.name} was successfully deleted!"
      redirect_to admin_categories_path
    end
  end

  private
    def category_params
      params.require(:category).permit(:name, :id)
    end
end

app/controllers/admin/images_controller.rb
class Admin::ImagesController < Admin::BaseController

  def index
    @images = Image.all
  end

  def new
    @image = Image.new
  end

  def create
    @image = Image.new(image_params)
    if current_admin?
      @image.save
      redirect_to admin_images_path
    else
      render :new
    end
  end

  private

  def image_params
    params.require(:image).permit(:name, :url)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :current_admin?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def current_admin?
    current_user && current_user.admin?
  end

end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :must_be_current_user

  def index
    @user = User.find(params[:user_id])
    @ideas = @user.ideas
  end

  def show
    @user = User.find(params[:user_id])
    @idea = @user.ideas.find(params[:id])
  end

  def new
    @user = User.find(params[:user_id])
    @idea = Idea.new
    @images = Image.all
  end

  def create
    @user = User.find(params[:user_id])
    @idea = @user.ideas.create(idea_params)
    IdeaImage.create(idea_id: @idea.id, image_id: params[:image_ids].first)
    if current_user
      @idea.save
      redirect_to user_ideas_path(@user)
    else
      render :new
    end
  end

  def edit
    @categories = Category.all
    @idea = Idea.find(params[:id])
  end

  def update
    @user = User.find(params[:user_id])
    @idea = @user.ideas.find(params[:id])
    @idea.update(idea_params)
    if @idea.save
      redirect_to user_idea_path(@idea.user, @idea)
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    Idea.destroy(params[:id])

    redirect_to user_ideas_path(@user)
  end

  private

  def idea_params
    params.require(:idea).permit(:title, :description, :category_id, :id)
  end

  def must_be_current_user
    if current_user && current_user != User.find(params[:user_id])
      render file: "/public/404"
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by_username(params[:username])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash[:notice] = "Username and/or password are not valid"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  private

    def user_params
      params.require(:user).permit(:username, :password, :email, :country)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/categories/index.html.erb
<h1> Admin Categories </h1>

<div class="create">
  <%= link_to 'Create New Category', new_admin_category_path %> <br>
</div>

<div class='cat'>
<% @categories.each do |category| %>
  <div id="list">
      <p><%= category.name %></p>
      <p><%= link_to "Delete", admin_category_path(category), method: "delete" %></p>
  </div>
<% end %>
</div>
<br><br>

app/views/admin/categories/new.html.erb
<%= form_for [:admin, @category] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/admin/images/index.html.erb
<h1> Admin Images </h1>

<div class="create">
  <%= link_to 'Create an Image', new_admin_image_path %> <br>
</div>

<div class='cat'>
<% @images.each do |image| %>
  <div id="list">
    <p><%= image.name %></p>
    <p><%= link_to 'image.url' %></p>
  </div>
<% end %>
<br><br>
</div>

app/views/admin/images/new.html.erb
<%= form_for [:admin, @image] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :url %>
  <%= f.text_field :url %>
  <%= f.submit %>
<% end %>

app/views/ideas/edit.html.erb
<%= form_for [current_user, @idea] do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.label :category_id %>
  <%= f.collection_select(:category_id, Category.all, :id, :name) %>
  <%= f.label :image_id %>
  <%= select_tag("image_ids", options_for_select(Image.all.collect { |image| [image.name, image.id] }, @idea.images.collect { |image| image.id}))%>

  <%= f.submit %>
<% end %>

app/views/ideas/index.html.erb
<h1> Ideas </h1>

<div class="create">
  <%= link_to 'Create a New Idea', new_user_idea_path(@user) %><br>
</div>

<div class='cat'>
  <% @user.ideas.each do |idea| %>
  <div id="list">
    <p>Title : <%= link_to "#{idea.title}", user_idea_path(@user, idea) %></p> <br>
    <p>Description : <%= idea.description %></p><br>
  </div>
  <% end %>
</div>

app/views/ideas/new.html.erb
<%= form_for [current_user, @idea] do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.label :category_id %>
  <%= f.collection_select(:category_id, Category.all, :id, :name) %>
  <%= f.label :image_id %>
  <%= select_tag("image_ids", options_for_select(Image.all.collect { |image| [image.name, image.id] }, @idea.images.collect { |image| image.id}))%>
  <%= f.submit %>
<% end %>

app/views/ideas/show.html.erb
<div class='show'>
Title : <%= @idea.title %><br>
Description : <%= @idea.description %><br><br>
<% @idea.images.each do |image| %><br>
  <%= image.name %><br>
<% end %>

<%= link_to "Edit", edit_user_idea_path(@user, @idea) %>
<br><br>
<%= button_to 'Delete', user_idea_path(@user, @idea), method: :delete %> <br>
<%= link_to 'Add An Image', edit_user_idea_path(@user, @idea) %> <br>
</div>

<div class='back'>
  <%= link_to 'Back to your ideas', user_ideas_path(@user) %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IdeaBox</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

    <body>
      <nav>
        <p>Idea Box</p>
        <ul>
          <li><%= link_to 'Welcome', root_path %></li>
          <li><%= link_to 'Log Out', logout_path %></li>

          <% if current_admin? %>
          <li><%= link_to 'Categories', admin_categories_path %></li>
          <li><%= link_to 'Images', admin_images_path %></li>
          <% end %>
        </ul>
        </nav>
      <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.label :email %>
  <%= f.email_field :email %>
  <%= f.label :country %>
  <%= f.text_field :country %>
  <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<h4> Welcome, <%= current_user.username %>!</h4>
<br>
<div class='show'>
  <%= link_to 'Your ideas', user_ideas_path(@user) %>
</div>

app/views/welcome/index.html.erb
<h1> Idea Box </h1>
  <div class="create">
    <%= link_to "Sign Up to be a New User", new_user_path %><br><br>
    <%= link_to 'I already have an account', login_path %><br>
  </div>

  <div class='cat'>
    <p> Afraid to forget your ideas ... We have the solution <p>
  </div>




</body>
</html>